# Generated by Django 4.2.16 on 2024-12-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_alter_session_parameter_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='arr_affinity_cookie',
            field=models.CharField(default='', max_length=300, verbose_name='ARR Affinity Cookie'),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='reconnection_limit',
            field=models.IntegerField(default=25, verbose_name='Limit Subject Screen Reconnection Trys'),
        ),
    ]
