# Generated by Django 4.2.16 on 2024-12-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_session_arr_affinity_cookie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='arr_affinity_cookie',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='ARR Affinity Cookie'),
        ),
    ]
